Migrate log traces to new Carto::Common::Logger
CartoDB/cartodb pull request #15776
Opened 2020-08-06 09:50 UTC by amiedes

2020-09-01 11:42 UTC, rafatower requested changes
Nice job with `log_context`. Nice distinction between `current_user` and `target_user`.

So good the file `lib/cartodb/logger.rb` is deleted.

I think the only change needed is to rollback the deletion of `remaining_days_deletion`

2020-09-01 11:42 UTC, rafatower commented on lib/resque/tracking_jobs.rb
> +        log_error(message: 'Carto::Tracking: Hubspot service error', event: { id: id }, params: params)
I'd rather write
```ruby
if code != '200' || body.blank?
  log_error(...)
end
```
which should be the exceptional path

2020-09-01 11:42 UTC, rafatower commented on spec/helpers/file_server_helper.rb
> +    rescue StandardError => e
I think the `rescue` block can be removed altogether

2020-09-01 15:50 UTC, amiedes commented on app/models/carto/helpers/user_commons.rb
> -  def remaining_days_deletion
Yes, but this method is both defined in `app/models/carto/helpers/user_commons.rb` and `app/models/carto/helpers/billing.rb` (with the exact same implementation), so it was duplicated.

2020-09-01 16:08 UTC, amiedes commented
@rafatower thanks for the suggestions 🙂 . I've applied some of them in the last commit.

Tomorrow I'll test this in staging.

2020-09-01 16:28 UTC, rafatower commented on app/models/carto/helpers/user_commons.rb
> -  def remaining_days_deletion
ohhh, didn't notice. Alright!

(Another thing to add to the toolbox: a duplicate code detector :grin: )

2020-09-01 16:28 UTC, rafatower approved these changes

2020-09-02 08:02 UTC, thedae approved these changes
Awesome job :)

2020-09-03 11:27 UTC, merged