CI check against growing sequel models
CartoDB/cartodb pull request #15800
Opened 2020-09-01 10:42 UTC by thedae

2020-09-01 13:23 UTC, rafatower approved these changes

2020-09-01 13:23 UTC, rafatower commented on .github/workflows/orm-check.yml
> +          done < <(git diff $(git merge-base $(git rev-parse HEAD) origin/master) --name-status)
Instead of just showing a warning if the model file is modified (which we're gonna have to do for sure), I'd just add the check for added lines, which can be achieved with something like:
```
git diff $(git merge-base $(git rev-parse HEAD) origin/master) --numstat
```

Nevertheless, improving upon this check may be a bit overkill, so leaving this up to you.

2020-09-01 15:11 UTC, thedae commented on .github/workflows/orm-check.yml
> +          done < <(git diff $(git merge-base $(git rev-parse HEAD) origin/master) --name-status)
I like it, let me see what I can do :)

2020-09-01 15:50 UTC, thedae commented on .github/workflows/orm-check.yml
> +          done < <(git diff $(git merge-base $(git rev-parse HEAD) origin/master) --name-status)
Done! Let me know if you have any other suggestion

2020-09-01 16:21 UTC, rafatower approved these changes
:clap: :clap:

2020-09-02 07:02 UTC, amiedes requested changes
@thedae is it possible that we print the name of the files that made the check fail in the log? I think you already wanted to do it but the interpolation is failing:

```log
2020-09-01T15:47:56.9908513Z [36;1mfi[0m
2020-09-01T15:47:56.9908820Z [36;1mexit 0[0m
2020-09-01T15:47:56.9947684Z shell: /bin/bash --noprofile --norc -e -o pipefail {0}
2020-09-01T15:47:56.9947809Z ##[endgroup]
2020-09-01T15:47:57.7060860Z ##[error]This file has been flagged to be migrated, please do not add new lines.
2020-09-01T15:47:57.7073613Z ##[error]Process completed with exit code 1.
2020-09-01T15:47:57.7082651Z Cleaning up orphan processes
```

2020-09-02 07:13 UTC, thedae commented
@amiedes I also though that at first, but I have been following github documentation about how to log warnings and errors: https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message

The interpolation seems to fail, but it is actually behaving like it should. Take a look at this failing workflow UI:
![image](https://user-images.githubusercontent.com/1104750/91943153-67773200-ecfc-11ea-8e82-bd96fc3360a8.png)

If we also want to see the filename in the raw logs, we could just add a new line, of course. What do you think?

2020-09-02 08:20 UTC, amiedes commented
I did not know that! Awesome job 🙂

2020-09-02 08:21 UTC, amiedes approved these changes

2020-09-04 09:45 UTC, merged