Now every user manages its own dbdirect IPs
CartoDB/cartodb pull request #15805
Opened 2020-09-02 14:48 UTC by thedae

Sync script to be executed in bch, this will clear redis and dump the dbdirect_ips from org owner to all users that belong to that org:

```ruby
Carto::User.find_each do |user|
  $users_metadata.DEL('dbdirect:' + user.username)
  if user.organization.present?
    if user.organization.owner != user
      user.dbdirect_effective_ips = user.organization.owner.dbdirect_effective_ips
      user.save!
    end
  end
  if user.dbdirect_effective_ips.any?
    $users_metadata.HSETNX('dbdirect:' + user.username, 'ips', user.dbdirect_effective_ips.join(','))
  end
end
```

2020-09-02 17:02 UTC, alasarr approved these changes

2020-09-03 06:41 UTC, amiedes requested changes
Nice work 🙂

I've just left a suggestion about some code that I think can be refactored a bit.

2020-09-03 06:41 UTC, amiedes commented on app/models/carto/user.rb
>    end
Given that `dbdirect_bearer` is now the same as `self.reload`, I think that:

```ruby
def dbdirect_effective_ips=(ips)
  ips ||= []
  bearer = dbdirect_bearer
  if bearer.dbdirect_ip
    bearer.dbdirect_ip.update!(ips: ips)
  else
    bearer.create_dbdirect_ip!(ips: ips)
  end
end

def dbdirect_effective_ip
  dbdirect_bearer.dbdirect_ip
end

def dbdirect_bearer
  reload
end
```

Could be rewritten as:

```ruby
def dbdirect_effective_ips=(ips = [])
  reload
  dbdirect_ip ? dbdirect_ip.update!(ips: ips) : create_dbdirect_ip!(ips: ips)
end

def dbdirect_effective_ip
  reload.dbdirect_ip
end
```

Could you check in local if it works as expected and apply it if relevant?

2020-09-03 06:43 UTC, thedae commented on app/models/carto/user.rb
>    end
Sure, I didn't want to remove the bearer logic just in case but I guess we can revert whenever we want :)

2020-09-03 07:19 UTC, thedae commented on app/models/carto/user.rb
>    end
Fixed, and seems to work. Thanks!

2020-09-03 09:15 UTC, amiedes approved these changes
🚀

2020-09-03 09:16 UTC, merged