Fixing logs for named maps
CartoDB/cartodb pull request #15826
Opened 2020-09-11 08:27 UTC by manmorjim

Some logs for named maps like this:

```json
{
  "visualization": {
    "id": "7d116384-b09e-42c4-9c2c-39bd36aadeac"
  },
  "action": "update",
  "request": {
    "url": "https://pellman1.carto.com:443/api/v1/map/named/tpl_7d116384_b09e_42c4_9c2c_39bd36aadeac?api_key=8f95327e43e214536a0bd3e9fe2433e25c9fb61a"
  },
  "response": {
    "status": 429,
    "body": "{\"errors\":[\"You are over platform's limits: too many requests. Please contact us to know more details\"],\"errors_with_context\":[{\"type\":\"limit\",\"message\":\"You are over platform's limits: too many requests. Please contact us to know more details\",\"subtype\":\"rate-limit\"}]}"
  },
  "timestamp": "2020-09-09T00:17:55.268+00:00",
  "levelname": "error",
  "cdb-user": "pellman1",
  "event_message": "Error in named maps API"
}
```

were not being indexed by Elastic due to the field `request` and `response` were storing JSON data whereas Elastic has defined those fields as String type.

In order to fix this I've flattened fields as String.

Also I've added `request_id` and `component` in `log_context`.

More info in CH: https://app.clubhouse.io/cartoteam/story/103253/some-logs-from-rails-are-not-being-ingested-in-kibana

2020-09-11 10:13 UTC, rafatower requested changes

2020-09-11 10:13 UTC, rafatower commented on lib/carto/named_maps/api.rb
> +        super.merge(request_id: Carto::CurrentRequest.request_id, component: 'cartodb.named-maps')
I'd use `cartodb.named-maps-client` not to confuse service and clients

2020-09-11 10:13 UTC, rafatower commented on lib/carto/named_maps/api.rb
> +          response_code: response.code,
This should be called `status` (and be an integer).

(Please check http://doc-internal.cartodb.net/platform/guidelines.html?highlight=logging#structure-of-log-messages and actual indices in kibana http://kibana.cartodb.net/app/kibana#/management/kibana/indices/c2f516f0-ee83-11ea-8d7e-13bea0b6446f?_g=()&_a=(tab:indexedFields) )

2020-09-11 10:13 UTC, rafatower commented on lib/carto/named_maps/api.rb
> +          response: response.body
Unfortunately the response field is used for something else (status code): http://kibana.cartodb.net/goto/96c8f2fe3b83fb39843b3ea92f4f4dff 

Better call it `response_body` so that filtering works as expected.

2020-09-11 12:44 UTC, rafatower approved these changes

2020-09-15 06:31 UTC, rafatower commented
Quick question: when do you plan to merge and deploy this?

2020-09-15 07:26 UTC, manmorjim commented
@rafatower I forgot this totally :man_facepalming: . Sorry! Merging and deploying this now!

2020-09-15 07:26 UTC, merged