Include Carto::ActiveRecordCompatibility in all Sequel models
CartoDB/cartodb pull request #15879
Opened 2020-09-28 15:48 UTC by amiedes

Fixes https://rollbar.com/carto/CartoDB/items/43071/?item_page=0&#instances

2020-09-30 07:36 UTC, rafatower requested changes
> Disable PG11 builds (production is already running PG12)

Please don't, there are still some running in pg11, sorry.

2020-09-30 07:36 UTC, rafatower commented on app/controllers/superadmin/organizations_controller.rb
> +    organizations_data = organizations.map { |organization| ::OrganizationPresenter.new(organization) }.map(&:data)
This is a matter of personal preference, but I'd like to raise a small discussion in context: don't you prefer the 80 chars limit instead of the 120? :stuck_out_tongue: 
- rationale for 120: any modern monitor has at least 120 chars wide.
- rationale for 80: you can more comfortably have 2 files or diffs open side-by-side

2020-09-30 07:36 UTC, rafatower commented on app/models/carto/helpers/active_record_compatibility.rb
> +  module ActiveRecordCompatibility
No big deal, but In retrospective, this should probably be
```ruby
module Carto
  module Helpers
    module ActiveRecordCompatibility
      # ...
    end
  end
end
```

(at least for the autoloader to work in dev)

2020-09-30 07:36 UTC, rafatower commented on app/models/organization.rb
> +  delegate :get_api_calls, to: :carto_organization
interesting (learning rails everyday)

2020-09-30 07:36 UTC, rafatower commented on app/models/carto/helpers/active_record_compatibility.rb
> +    def model_name
is this used anywhere? I see this comes from the `SequelFormCompatibility` and was added to the `::User` but no usage of it (coverband says so, the safe thing to do is to keep it here...)

I think this was done in the context of the migration to Rails 4

https://api.rubyonrails.org/classes/ActiveModel/Naming.html

2020-09-30 07:36 UTC, rafatower commented on app/presenters/organization_presenter.rb
> +  def visualizations_builder
IMO this method should be private, not exposed by a presenter. Perhaps all the methods below.

2020-09-30 07:36 UTC, rafatower commented on app/presenters/base_presenter.rb
> +  def method_missing(*args, &block)
Not sure the presenter should allow that (I know someone who truly dislikes these "magic methods").

Are there actual or expected usages for the `OrganizationPresenter`?

2020-09-30 07:54 UTC, amiedes commented on app/presenters/organization_presenter.rb
> +  def visualizations_builder
Hmmm... there is a `private` statement on line 7 😄

2020-09-30 08:08 UTC, amiedes commented on app/controllers/superadmin/organizations_controller.rb
> +    organizations_data = organizations.map { |organization| ::OrganizationPresenter.new(organization) }.map(&:data)
I've moved this debate to https://cartoteam.slack.com/archives/C01BB961YKX/p1601452698001800 🤣

2020-09-30 08:12 UTC, amiedes commented on app/models/carto/helpers/active_record_compatibility.rb
> +  module ActiveRecordCompatibility
Indeed this should be a [`ActiveSupport::Concern`](https://api.rubyonrails.org/classes/ActiveSupport/Concern.html) and go under `app/models/concerns` like what we did with https://github.com/CartoDB/cartodb/blob/master/app/models/concerns/cartodb_central_synchronizable.rb (BTW, the `Concern` namespace is not needed, the Rails default directories don't count when doing the module namespacing).

I'm going to change it since I'm up to everything related to following the autoloader conventions. In Rails 6 the autoloader library changes to https://github.com/fxn/zeitwerk, so the more we follow the conventions the easier it'll be in the future.

2020-09-30 08:14 UTC, amiedes commented on app/models/carto/helpers/active_record_compatibility.rb
> +    def model_name
In this case I'd leave it there, since it's one of those methods that sometimes is "magically" by Rails under the hood to process some of the conventions.

2020-09-30 08:19 UTC, amiedes commented on app/presenters/base_presenter.rb
> +  def method_missing(*args, &block)
Indeed this is what allows doing things like:

```ruby
class OrganizationPresenter < BasePresenter

  def default_representation
    {
      created_at: created_at,
      description: description,
      id: id
    }
  end

end
```

Instead of the more verbose:

```ruby
class OrganizationPresenter < BasePresenter

  def default_representation
    {
      created_at: object.created_at,
      description: object.description,
      id: object.id
    }
  end

end
```

I've used this pattern quite often for implementing Presenters, Decorators, FormObjects etc. Personally I find it very useful and haven't had much trouble with it. But I'm open to changing it if you deem aproppiate 🙂

2020-09-30 08:20 UTC, amiedes commented
> Please don't, there are still some running in pg11, sorry.

Yep you're right. The metadata DB is already in PG12 but we still have some clients in PG11 :(

2020-09-30 08:43 UTC, rafatower commented on app/presenters/organization_presenter.rb
> +  def visualizations_builder
arg! right, my bad, sorry for the noise :(

2020-09-30 08:45 UTC, rafatower commented on app/controllers/superadmin/organizations_controller.rb
> +    organizations_data = organizations.map { |organization| ::OrganizationPresenter.new(organization) }.map(&:data)
ok, let me add this example to that thread

2020-09-30 09:24 UTC, rafatower commented on app/presenters/base_presenter.rb
> +  def method_missing(*args, &block)
Okay, I can buy it if you make `method_missing` private, so that you can define subclasses with that syntax but you cannot do things like this:

```ruby
presenter = OrganizationPresenter.new(@organization)
presenter.quota_in_bytes = 42
presenter.save!
```

2020-09-30 09:25 UTC, rafatower commented on app/presenters/base_presenter.rb
> +  def respond_to_missing?(method_name, _include_private = false)
I'd remove this

2020-09-30 09:29 UTC, rafatower commented
> > Please don't, there are still some running in pg11, sorry.
>
> Yep you're right. The metadata DB is already in PG12 but we still have some clients in PG11 :(

It is true that it mostly affects metadata, but some classes also connect to the user's DB... in the end it is a matter of cost-benefit (tests are run in parallel for pg11 and 12, but we could save some bucks). I'd wait a little bit more and disable in a different PR. Aside, I think this needs changes somewhere else.

2020-10-01 16:38 UTC, rafatower approved these changes

2020-10-02 11:51 UTC, merged