Migrate and delete ClientApplication Sequel model
CartoDB/cartodb pull request #15886
Opened 2020-10-06 16:01 UTC by thedae

2020-10-08 09:26 UTC, amiedes requested changes
Nice work 🎉. I'm glad to see each day we're getting closer to removing these damn models 🙂 

I've left some minor comments which should be easy to fix

2020-10-08 09:26 UTC, amiedes commented on app/services/carto/user_metadata_export_service.rb
> +      client_application.secret = client_app_hash[:secret]
Another way of achieving this could be to modify the [model callbacks](https://github.com/CartoDB/cartodb/blob/chore/ch106931/migrate-and-delete-clientapplication-model/app/models/carto/client_application.rb#L50-L53) so those attributes are only assigned if not present yet, for example:

```ruby
def initialize_entity
  self.key = OAuth::Helper.generate_key(40)[0, 40] unless key.present?
  self.secret = OAuth::Helper.generate_key(40)[0, 40] unless secret.present?
end
```

I don't have a strong opinion on this so choose what you think it's more intuitive to understand.

Maybe `created_at` is not overwritten by Rails if you pass it as an argument to the model constructor, but for `updated_at` you'll have to force it anyways.

2020-10-08 09:26 UTC, amiedes commented on spec/services/carto/user_metadata_export_service_spec.rb
> +      Carto::ClientApplication.where(user_id: @user.id).each(&:destroy)
I think that now that you've fixed the 1-1 relationship, this could be rewritten as:

```ruby
user.client_application.destroy
```

2020-10-08 09:26 UTC, amiedes commented on app/models/carto/client_application.rb
> +end
Ruby and Rails have a set of rules about how directories/classes should be named in order for the autoloader to work more seamlessly, and avoid to manually having to write explicitly things such as `require_relative` or `require_dependency`.

I know this code is just a port from the previous model, but if you feel like so you could move the `DomainPatcherRequestProxy` class to its own file in order to follow the conventions.

I this case i'd move it to `lib/domain_patcher_request_proxy.rb` since it's not per se a model, and you'll have to manually `require` it anyways since `lib` contents are not loaded in Rails by default.

For more info you can check the [Zeitwerk documentation](https://github.com/fxn/zeitwerk#file-structure), which is the autoloader of Rails 6 (but the conventions exists from earlier).

2020-10-08 09:41 UTC, thedae commented on app/models/carto/client_application.rb
> +end
Totally agree: having several classes in the same file is totally agains any kind of autoloader (and not only for Ruby)

2020-10-09 07:09 UTC, amiedes approved these changes
👍

2020-10-09 07:18 UTC, merged