[ch113184] Error importing KML files with slashes in 'name' nodes
CartoDB/cartodb pull request #15897
Opened 2020-10-22 11:11 UTC by Shylpx

### Resources

- [Clubhouse story](https://app.clubhouse.io/cartoteam/story/113184/aaranzadi-error-while-trying-to-delete-a-dataset)

### Changes

- When a KML is imported, sanitize the layer names of the file before create one file by layer using that names.
- Minor Rubocop fixes.

2020-10-22 12:29 UTC, Algunenano commented
Can you please explain the relation between the CH ticket and this? Maybe it's wrong. Also, pinging @jgoizueta since he has been solving many issues in the different importers similar to this one and he's aware of the many implications a change like this can have in the service.

2020-10-22 12:40 UTC, Shylpx commented
@Algunenano You are right, I was working with another story and I added the wrong one. It is updated now.

2020-10-22 13:56 UTC, amiedes requested changes
Just some minor comments. Good work and good idea trying to reuse core rails methods 💪 🎉

2020-10-22 13:56 UTC, amiedes commented on services/importer/lib/importer/kml_splitter.rb
> +      #       https://apidock.com/rails/v5.2.3/ActiveStorage/Filename/sanitized
Good idea! Such a pity we're still in Rails 4 and can't call directly that method without adding a dependency to `ActiveStorage`

2020-10-22 13:56 UTC, amiedes commented on services/importer/spec/acceptance/kml_spec.rb
> +                               pg: @user.db_service.db_configuration_for,
Could you please address these linter warnings?

2020-10-22 13:56 UTC, amiedes commented on services/importer/spec/fixtures/multiple_layer_with_problematic_names.kml
> +<?xml version="1.0" encoding="UTF-8"?>
(just a personal opinion)

Sometimes I find big fixture files a bit hard to maintain, because I it makes a bit difficult to understand what the test is actually trying to achieve. Do you think it would be easy to modify this `kml` so in includes just the necessary information for the import to work and for the sanitization to be tested? (for example, just 1 layer with 1 point)

Said this, I have almost 0 knowledge about how this files work and this carto, so judge yourself and whatever you decide to do will be 👍

2020-10-22 13:58 UTC, amiedes commented on services/importer/spec/acceptance/kml_spec.rb
> +  it 'imports multi-layer KMLs with problematic names' do
Do you think something like `'imports multi-layer KMLs with slashes on the name'` would be more descriptive?

2020-10-23 09:20 UTC, Shylpx commented on services/importer/spec/fixtures/multiple_layer_with_problematic_names.kml
> +<?xml version="1.0" encoding="UTF-8"?>
Absolutely, I'm going to minify the file as much as possible.

2020-10-27 09:16 UTC, jgoizueta commented
Hey, a couple of questions to have in mind:

The final names of tables generated by imports are sanitized and adapted to PG requirements here:
https://github.com/CartoDB/cartodb/blob/97688bf29754d5dd504d09853e9264126463ab66/app/models/table.rb#L1298-L1305

But for KML layers we need first to make sure we have names that are valid for the filesystem.

And we have to take care with existing sync tables: if we change the name of the generated table we make break them. This means we should alter only layer names that would cause errors (invalid file names) and not layer names that currently cause no error, so could be in use in some sync, or we could make sure the transmormations performed are consistent with `get_valid_name`. I'm not sure it would be a good idea to use the  method `get_valid_name` itself here, since it also avoids table name collisions, so it may not be idempotent, and I don't like the idea of checking user tables names here too.

😅  Hey I feel I'm bringing too much complication into a simple matter 🤔  I'm tempted to check if there are any sync tables at all in production using KML files, if there aren't we could save ourselves some trouble. If we know KML syncs aren't too common I wouldn't care for these details.

2020-10-27 09:44 UTC, jgoizueta commented
We also have this intented to produced valid file names (and it seems used by Carto::ValidTableNameProposer

https://github.com/CartoDB/cartodb/blob/97688bf29754d5dd504d09853e9264126463ab66/lib/carto/file_system/sanitize.rb#L7-L13

Maybe the ActiveStorage method is more comprehensive, but I think this will be good enough for our purposes, and since it's been used finally for filenames there should be less chance of altering the final result.

2020-10-27 09:47 UTC, jgoizueta requested changes
I would use `Carto::FileSystem::Sanitize.sanitize_identifier` for consistency with table naming and other uses.

If you find the `ActiveStorage` sanitize method has some advantage I would incorporate it into our method (but beware of altering existing syncs).

2020-10-27 09:47 UTC, jgoizueta commented on services/importer/lib/importer/kml_splitter.rb
> +        layer_name.encode(Encoding::UTF_8, invalid: :replace, undef: :replace, replace: 'ï¿½')
I don't know the original reason (in ActiveStorage) of the funny replacement string, but wouldn't `-` or `_` be nicer? ( (I guess it's for making invalid strings to stand out)

2020-10-27 11:38 UTC, Shylpx commented
@jgoizueta Thank you very much, I think using `Carto::FileSystem::Sanitize.sanitize_identifier` is the best approach. This way we keep the consistency without the need of checking the existent sync KML tables, and at the same time we are solving the problem by removing the slashes from the KML layer names.

2020-10-28 15:04 UTC, jgoizueta approved these changes
🏁

2020-10-29 14:24 UTC, amiedes approved these changes

2020-11-03 11:54 UTC, merged