Feature/ch119096/subscription in clouds to process map views
CartoDB/cartodb pull request #15969
Opened 2020-12-01 16:33 UTC by juanrmn

WIP

2020-12-10 08:12 UTC, thedae commented on app/models/concerns/cartodb_central_synchronizable.rb
> +           discus_shortname twitter_username geocoding_quota map_views_quota
Just one question: if this field has been updated for the central sync process, shouldn't this modification also be applied in Central code?

2020-12-10 08:15 UTC, thedae commented on lib/carto/subscribers/map_views_update.rb
> +require './lib/carto/user_creator'
Do we need these dependencies? Looks like a copy&paste

2020-12-10 08:19 UTC, thedae requested changes
Apart from a minor improvement, please update the `lib/sql` submodule before merging :)

The rest is looking good!

2020-12-10 08:19 UTC, thedae commented on lib/carto/subscribers/map_views_update.rb
> +require './lib/carto/user_creator'
Do we need these dependencies? Looks like a copy&paste

2020-12-10 08:32 UTC, juanrmn commented on app/models/concerns/cartodb_central_synchronizable.rb
> +           discus_shortname twitter_username geocoding_quota map_views_quota
You're totally right, I had this one as Draft: :facepalm: : https://github.com/CartoDB/cartodb-central/pull/2992

2020-12-10 08:57 UTC, juanrmn commented on lib/carto/subscribers/map_views_update.rb
> +require './lib/carto/user_creator'
Done.

2020-12-16 11:10 UTC, thedae approved these changes
:+1:

2021-01-13 12:13 UTC, merged