Feature/ch122158/tilesets tabs list
CartoDB/cartodb pull request #16063
Opened 2021-01-20 13:59 UTC by Josmorsot

2021-01-20 15:37 UTC, padawannn requested changes

2021-01-20 15:37 UTC, padawannn commented on lib/assets/javascripts/new-dashboard/components/QuickActions/TIlesetQuickActions.vue
> +    isSubscription () {
I think that we can remove this method

2021-01-20 16:14 UTC, VictorVelarde commented on lib/assets/javascripts/new-dashboard/components/QuickActions/TIlesetQuickActions.vue
> +    openQuickactions () {
How about naming like openQuickActions ?

2021-01-21 08:16 UTC, Josmorsot commented on lib/assets/javascripts/new-dashboard/components/QuickActions/TIlesetQuickActions.vue
> +            shouldBeHidden: this.isSubscription
QuickActions is not finished. It's only the copy of DatasetQuick actions but with only one option. Please, ignore it for know

2021-01-21 08:16 UTC, Josmorsot commented on lib/assets/javascripts/new-dashboard/components/QuickActions/TIlesetQuickActions.vue
> +    isSubscription () {
QuickActions is not finished. It's only the copy of DatasetQuick actions but with only one option. Please, ignore it for know

2021-01-21 08:20 UTC, Josmorsot commented on lib/assets/javascripts/new-dashboard/components/QuickActions/TIlesetQuickActions.vue
> +    openQuickactions () {
Sure! I think that is a typo, also in file name. I'll fix it in the next PR

2021-01-21 10:00 UTC, padawannn approved these changes

2021-01-21 10:00 UTC, merged