update to Carto::Organization
CartoDB/cartodb pull request #16060
Opened 2021-01-19 15:29 UTC by alberhander

Update `Organization` with `Carto::Organization` for some tasks used by onpremises.

2021-01-19 16:33 UTC, Shylpx requested changes
I have reviewed the PR, but cc @amiedes, could you take a look just in case something should be taken into consideration regarding the `Organization` model migration?

2021-01-19 16:33 UTC, Shylpx commented on lib/tasks/db_maintenance.rake
> +      Carto::Organization.each do |org|
Is this working? :thinking: AFAIK there is no `each` for `ActiveRecord` models. You could use `find_each` (better), or `all.each` (it loads all the records in memory):
```ruby
Carto::Organization.find_each do |org|
```

2021-01-19 16:33 UTC, Shylpx commented on lib/tasks/db_maintenance.rake
> +      organization  = Carto::Organization.find_by(:name=> args[:organization_name]).first
`find_by` method already returns only one element, the first found that meets the conditions, so the `first` method should be avoided. I guess `filter` would be equivalent to `where`, that retrieves all record meeting the conditions:

```ruby
organization = Carto::Organization.find_by(name: args[:organization_name])
```
Or
```ruby
organization = Carto::Organization.where(name: args[:organization_name]).first
```

2021-01-19 16:33 UTC, Shylpx commented on lib/tasks/db_maintenance.rake
> +      organization  = Carto::Organization.find_by(:name=> args[:organization_name]).first
The same as above.

2021-01-19 16:33 UTC, Shylpx commented on lib/tasks/db_maintenance.rake
> +      organization = Carto::Organization.find_by(:name=> args[:organization_name]).first
The same as above.

2021-01-19 16:33 UTC, Shylpx commented on lib/tasks/db_maintenance.rake
> +      organization = Carto::Organization.find_by(:name => ENV['ORGANIZATION_NAME']).first
The same as above.

2021-01-19 16:33 UTC, Shylpx commented on lib/tasks/db_maintenance.rake
> +      organization = Carto::Organization.find_by(:name => ENV['ORGANIZATION_NAME']).first
The same as above.

2021-01-19 16:33 UTC, Shylpx commented on lib/tasks/db_maintenance.rake
> +      organization = Carto::Organization.find_by(name: org_name).first
The same as above.

2021-01-19 20:45 UTC, sabman commented on lib/tasks/db_maintenance.rake
>          owner = o.owner
While testing this I have noticed a cascading error. This owner variable, prior to the change was the sequel `User` model. now it will be the activerecord `Carto::User` model. 

The method `install_and_configure_geocoder_api_extension` is not defined `Carto::UserDBService` (associcated with the activerecord `User`) but rather in `CartoDB::UserModule::DBService` (associated with the sequel `User` class)
 
This leads to this `owner.db_service.setup_organization_role_permissions` failing since activerecord references a different `db_service` class (`Carto::UserDBService`) to the old sequel class which referenced `CartoDB::UserModule::DBService`. see  [line 1124](https://github.com/CartoDB/cartodb/pull/16060/files#diff-0e5eb18dfe72990ce590cd47d92bce9aae4999c98b548acb4a6daf135f3f65b4R1124)

2021-01-20 07:18 UTC, amiedes commented on lib/tasks/db_maintenance.rake
> +      organizations = args[:organization_name].present? ? Carto::Organization.where(name: args[:organization_name]).all : Carto::Organization.all
I think the `all` in:

```ruby
Carto::Organization.where(name: args[:organization_name]).all
```

is redundant (not a bit issue, just for you to know)

2021-01-20 07:23 UTC, amiedes requested changes
Just some minor comments apart from what @Shylpx already pointed out

2021-01-20 07:23 UTC, amiedes commented on lib/tasks/db_maintenance.rake
>          owner = o.owner
Yes, this is a known issue, but will continue to happen until all the models have been migrated to `ActiveRecord`. The current way to bypass this should be:

```ruby
o.owner.sequel_user
```

2021-01-20 07:23 UTC, amiedes commented on lib/tasks/db_maintenance.rake
> +      organizations = args[:organization_name].present? ? Carto::Organization.where(name: args[:organization_name]).all : Carto::Organization.all
I think the `all` in:

```ruby
Carto::Organization.where(name: args[:organization_name]).all
```

is redundant (not a big issue, just for you to know)

2021-01-20 07:23 UTC, amiedes commented on lib/tasks/db_maintenance.rake
> +      organizations = args[:organization_name].present? ? Carto::Organization.where(name: args[:organization_name]).all : Carto::Organization.all
Same as above

2021-01-20 07:23 UTC, amiedes commented on lib/tasks/db_maintenance.rake
> +      organizations = args[:organization_name].blank? ? Carto::Organization.all : Carto::Organization.where(name: args[:organization_name]).all
Same as above

2021-01-20 07:23 UTC, amiedes commented on lib/tasks/db_maintenance.rake
> +      org = Carto::Organization.find_by(:name=> args[:orgname])
Could you please address these linter issues? Should be enough with:

```ruby
Carto::Organization.find_by(name: args[:orgname])
```

2021-01-20 08:59 UTC, alberhander commented
Thanks a lot @Shylpx @amiedes!! I guess this was working for me because I was only running a little part of this code. I'll make the requested changes!

2021-01-20 14:49 UTC, alberhander reviewed
Added requested changes

2021-01-20 15:19 UTC, amiedes approved these changes
@alberhander I'm approving the PR but please address the issue pointed out by @sabman.

Thanks for fixing this by the way 🙂 , for some reason I forgot to update the calls to the old model in this file when I did the migration some months ago 🤷

2021-01-20 15:19 UTC, amiedes commented on lib/tasks/db_maintenance.rake
>          owner = o.owner
@alberhander could you please take care of this 🙏  (I'm approving the PR anyways so I don't add 1 more interaction delay for you)

2021-01-21 09:11 UTC, Shylpx approved these changes

2021-01-27 08:00 UTC, amiedes approved these changes
👍

2021-01-27 09:19 UTC, merged