added new message for firsttimeInDashboard
CartoDB/cartodb pull request #16159
Opened 2021-02-16 05:59 UTC by Josmorsot

2021-02-16 08:53 UTC, padawannn commented
Change this PR against connectors

2021-02-16 09:04 UTC, padawannn requested changes

2021-02-16 09:04 UTC, padawannn commented on lib/assets/javascripts/new-dashboard/pages/Home/ConnectionsSection/ConnectionsSection.vue
> +<template>
unlike datasetSection and MapSection, I think that ConnectionsSection component is not necessaryy

2021-02-16 09:04 UTC, padawannn commented on lib/assets/javascripts/new-dashboard/pages/Data/Connections/Connections.vue
> +      this.$emit('newConnectionClicked');
It's not necessary to emit a  newConnectionClicked event, instead replace this `<button @click="createConnection" class="button is-primary">{{ $t(`DataPage.zeroCase.createDataset`) }}</button>` by 
`<router-link :to="{ name: 'new-connection' }" v-if="connections.length">
              <button class="button is-primary">{{ $t(`DataPage.newConnection`) }}</button>
            </router-link>`

2021-02-16 11:58 UTC, padawannn approved these changes

2021-02-17 17:02 UTC, merged

2021-03-04 10:39 UTC, rafatower commented
:robot: please make sure all the checks pass before merging @Josmorsot @padawannn