Ivan/dataset searcher
CartoDB/cartodb pull request #16167
Opened 2021-02-19 08:05 UTC by Josmorsot

2021-02-19 13:03 UTC, padawannn requested changes

2021-02-19 13:03 UTC, padawannn commented on package.json
> +    "@carto/viewer": "CartoDB/viewer#refinement",
change the viewer version

2021-02-19 13:03 UTC, padawannn commented on script/ci/cloudbuild-tests-pr-pg12.yaml
> +  timeout: 2700s
why this?

2021-02-19 13:06 UTC, Josmorsot commented on script/ci/cloudbuild-tests-pr-pg12.yaml
> +  timeout: 2700s
It has been added by @alberhander, to solve a problem with CI

2021-02-19 13:07 UTC, padawannn approved these changes

2021-02-22 12:58 UTC, merged

2021-03-04 10:35 UTC, rafatower commented
:robot: please make sure all the checks pass before merging @Josmorsot