Feature/ch132964/sync api keys both in on prem and associated fix specs 3
CartoDB/cartodb pull request #16205
Opened 2021-03-08 16:06 UTC by amiedes

2021-03-09 12:37 UTC, rafatower commented on app/models/carto/api_key.rb
> +        { type: type, token: token, user_id: user_id, username: user.username }
Note to myself: sending both `user_id` *and* `username`, important to relay remote creation messages

2021-03-09 15:18 UTC, rafatower requested changes
Sorry, but we have to address a (potential) message ordering issue. After that I think it can be merged.

The rest looks fine to me. Of course you got a special waiver to ignore rubocop complaints in test code, as you had to modify a ton of specs.

2021-03-09 15:18 UTC, rafatower commented on app/models/carto/api_key.rb
> +    after_create :create_remote_do_api_key, if: ->(api_key) { api_key.master? }
just an opinion: I like more the syntax we use in Central
```ruby
after_create(:create_remote_do_api_key, if: :master?)
```

(I understand you do need a block or a new function predicate for the check below (regenerate callback))
(as an opinion and likes and dislikes you're entitled to completely ignore it)

2021-03-09 15:18 UTC, rafatower commented on app/models/carto/api_key.rb
> +    def regenerate_remote_do_api_key
Sorry, but we need a specific message here: there's no guarantee on the order of the messages, and the likelihood of the "create" to overtake the "destroy" is pretty high in this case.

I think it is safer to have a specific message/command `:regenerate_remote_do_api_key` almost for the same price.

2021-03-10 07:30 UTC, rafatower commented on app/models/carto/api_key.rb
> +    def regenerate_remote_do_api_key
After our chat and for the record: it is OK as worst case scenario is  having an old api key in redis for a short while, as old and new have different redis keys.

OTOH that triggered the need for this: https://github.com/CartoDB/data-observatory/pull/1010

2021-03-10 08:05 UTC, amiedes commented on app/models/carto/api_key.rb
> +    after_create :create_remote_do_api_key, if: ->(api_key) { api_key.master? }
Thanks for the suggestion 👍 . I agree with you and will try to remember this for the next time, but for (lazyness? 😅 ) I'm going to deploy it like it's now to avoid having to wait for the build again and potentially having to do a retry

2021-03-10 08:05 UTC, merged