Feature/ch140110/move viewer into cartodb
CartoDB/cartodb pull request #16222
Opened 2021-03-16 12:17 UTC by Josmorsot

2021-03-16 13:30 UTC, VictorVelarde commented on lib/assets/javascripts/dashboard/statics/static.js
> +    var userFeatureFlags = userData ? userData.feature_flags : [];
ok, I guess those are not required here

2021-03-16 13:32 UTC, VictorVelarde commented on lib/assets/javascripts/dashboard/statics/static.js
> +      markAsReady(userData);
Why the refactor here on this part?

2021-03-16 13:32 UTC, VictorVelarde commented on lib/assets/javascripts/new-dashboard/pages/TilesetsViewer.vue
> +            baseUrl: `${this.base_url}/viewer`,
👏🏻  Nice job

2021-03-16 13:34 UTC, VictorVelarde commented on lib/assets/javascripts/tilesets-viewer/App.vue
> +      return { username: regex[1], type: regex[2] };
Will this pattern work in users within organizations?

2021-03-16 13:36 UTC, VictorVelarde commented on lib/build/files/webpack_files.js
> +    anonymous: true,
I guess we're sure about this anonymous, right?

2021-03-16 13:37 UTC, VictorVelarde commented on package.json
> +    "dev:tilesets-viewer": "NODE_ENV=development vue-cli-service serve --watch lib/assets/javascripts/tilesets-viewer/main.js",
Seems like the pattern worked well for do-catalog 👍🏻

2021-03-16 13:38 UTC, VictorVelarde commented on webpack/static-pages/webpack.dev.config.js
> +          './node_modules/@carto/viewer'
I guess this was your original issue, right? having that excluded...

2021-03-16 13:40 UTC, VictorVelarde commented on webpack/static-pages/webpack.prod.config.js
> +    rules: [
If the config is the same for prod & dev I think we should try to avoid duplication here, can we?

2021-03-16 13:41 UTC, VictorVelarde commented on package.json
> +  "version": "1.0.0-assets.232",
Could you please add a suffix and deploy to staging for review?

2021-03-16 13:42 UTC, VictorVelarde requested changes
LGTM, just some (minor comments). 

Before merging I think we would need a staging env + also some clear steps for testing (for example including users from an org).

2021-03-16 14:00 UTC, Josmorsot commented on lib/assets/javascripts/dashboard/statics/static.js
> +      markAsReady(userData);
new viewer can be accessed as anon. user. I need to duplicate a piece of code that was not called when user is not authenticated. So I prefer move this piece to a new function.

2021-03-16 14:01 UTC, Josmorsot commented on lib/assets/javascripts/tilesets-viewer/App.vue
> +      return { username: regex[1], type: regex[2] };
Should be, the tilesets viewer shouldn't need the organization name because usernames are unique (right?).

2021-03-16 14:02 UTC, Josmorsot commented on lib/build/files/webpack_files.js
> +    anonymous: true,
It's the only way to avoid call the authentication methods that are being injected. With this new flag we can render static pages for anon. users

2021-03-17 07:29 UTC, padawannn requested changes

2021-03-17 07:29 UTC, padawannn commented on lib/assets/javascripts/tilesets-viewer/App.vue
> +        // FIXME: we need to add `mapsUrl`, it should change depends on environment. What about `region`?
We can't merge without solving this. Maybe we could include the region in the public URL

2021-03-17 07:29 UTC, padawannn commented on lib/assets/javascripts/tilesets-viewer/main.scss
> +$color-primary: #2E51E8;
All these styles are necessary? Viewer has its own styles

2021-03-17 08:20 UTC, Josmorsot commented on lib/assets/javascripts/tilesets-viewer/App.vue
> +        // FIXME: we need to add `mapsUrl`, it should change depends on environment. What about `region`?
we think that i should be solved. But we need to try first in staging

2021-03-17 08:21 UTC, Josmorsot commented on lib/assets/javascripts/tilesets-viewer/main.scss
> +$color-primary: #2E51E8;
sure, probably I can remove it

2021-03-31 09:46 UTC, closed without merging