[Reef] Set up SSO: Check whether the user was created via SAML to logout
CartoDB/cartodb pull request #16253
Opened 2021-04-13 08:25 UTC by manmorjim

2021-04-14 07:40 UTC, manmorjim commented on spec/requests/sessions_controller_spec.rb
> -    end
I removed these tests because I think they don't make sense.

They were testing SAML logout operations without the username, this is, the URL was the form:

`http://{organization_name}.localhost.lan:3000/logout`

These tests were working because SAML logout did not need the user. But now, we need the user in order to check if they were created via SAML or CARTO to logout using the right way.

Anyway I think these test are irrelevant because I think we don't have the case where no username is provided within the URL to logout via SAML

2021-04-14 07:41 UTC, manmorjim commented on app/models/user.rb
>    private
making `created_via` public

2021-04-14 07:45 UTC, thedae requested changes
Almost there, just a minor suggestion

2021-04-14 07:45 UTC, thedae commented on app/models/user.rb
> +  def created_via
Can we move this method to `UserCommons`? By doing that, it will be available for both Sequel and AR based users and we can get rid of the `user.sequel_user...` line in the `sessions_controller` :)

2021-04-14 07:46 UTC, thedae commented on app/models/user.rb
> +  def created_via
Well, actually not `get rid of` the line, but modifying it so it doesn't use the Sequel model but AR one

2021-04-14 12:41 UTC, thedae approved these changes
:+1: !

2021-04-14 14:15 UTC, merged

2021-04-15 06:43 UTC, amiedes commented on spec/requests/sessions_controller_spec.rb
> -    end
This tests caused me a lot of pain and was tempted to remove them. Finally managed to fix them, but always found them very confusing.

Glad you got rid of them!