refactor to use do-catalog as embedded component in CARTO Workspace
CartoDB/cartodb pull request #16325
Opened 2021-08-03 13:04 UTC by Josmorsot

https://app.clubhouse.io/cartoteam/story/171486/data-catalog-embed-do-catalog-as-new-section

2021-08-06 08:57 UTC, VictorVelarde approved these changes
🚀 It looks fine. Just be sure to plan a QA session coordinated with the deployment.

Remember that there are 2 PRs to create:
- this one, to apply it to CARTODB
- another PR, after publication, on PUBLIC Website pointing to public assets

2021-08-06 08:58 UTC, VictorVelarde requested changes
Code looks good, but CI must be green before merging

2021-08-06 09:07 UTC, Jesus89 commented on package.json
> +    "build:do-catalog": "NODE_ENV=production vue-cli-service build --watch --target lib --name do-catalog --formats umd-min --no-clean --inline-vue lib/assets/javascripts/do-catalog/main.js",
I think `--watch` may not be needed here

2021-08-06 12:13 UTC, VictorVelarde commented on package.json
> +    "build:do-catalog": "NODE_ENV=production vue-cli-service build --watch --target lib --name do-catalog --formats umd-min --no-clean --inline-vue lib/assets/javascripts/do-catalog/main.js",
true-thing

2021-08-09 10:10 UTC, VictorVelarde commented on NEWS.md
> +* Update DO Catalog dependecies and some changes to use bundle on CARTO Workspace [#16325](https://github.com/CartoDB/cartodb/pull/16325)
TYPO: dependencies

2021-08-09 17:46 UTC, VictorVelarde approved these changes
🚀

2021-08-09 17:47 UTC, VictorVelarde commented
PR looks good, but please link staging url in card, so @AnaDiaz85 can test also catalog there

2021-08-11 13:50 UTC, merged