Fix auto guessing when importing CSV
CartoDB/cartodb pull request #16326
Opened 2021-08-04 08:57 UTC by moicalcob

### Resources

[Clubhouse story](https://app.clubhouse.io/cartoteam/story/159377/import-api-guessing-falls-back-with-wrong-dates)

### Context

When a user tries to import a CSV file with wrong fields the auto guessing feature is not working. The CSV should be imported trying to guess the rest of the columns.

### Changes

- [x]  Import CSV with wrong fields without disabling auto guessing.
- [x]  Add tests

2021-08-06 12:00 UTC, Shylpx requested changes

2021-08-06 12:02 UTC, Shylpx commented
Nice job @moicalcob! :smile:, I just added a few tips to improve the readability. :rocket:

2021-08-06 13:59 UTC, amiedes requested changes
Nice catch 💪  . I've left a few comments which should be easy to address, ping me if you have any doubts or want to discuss anything further 🙂 .

2021-08-06 13:59 UTC, amiedes commented on services/importer/spec/acceptance/csv_spec.rb
> +    age.class.should eq Integer
Indeed I'd favor `expect(age).to be_an(Integer)`

https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/type-matchers

2021-08-06 13:59 UTC, amiedes commented on services/importer/spec/acceptance/csv_spec.rb
> +  it 'auto guessing should work in csv columns if one field is causing troubles' do
I'd try to be more explicit in the test description about what its "causing troubles". Taking a look at the CSV maybe could be: `it 'guesses field types correctly when the CSV contains invalid dates'` or something like that.

2021-08-06 13:59 UTC, amiedes commented on services/importer/spec/fixtures/wrong_date_auto_guessing.csv
> +age,date,name
I'd try to reduce this file to the minimum text needed to reproduce the issue as that helps keeping clear the intent  of the test case.

I'm not 100% familiar with the ticket but maybe this should be enough?

```csv
age,date
20,2000-01-01
21,2000-1-NA
```

2021-08-06 14:01 UTC, amiedes commented
In case you're curious about why I'm suggesting this:

> Indeed I'd favor expect(age).to be_an(Integer)

https://github.com/rspec/rspec-expectations/blob/master/Should.md#why-switch-over-from-should-to-expect

2021-08-09 09:57 UTC, moicalcob commented on services/importer/lib/importer/loader.rb
> +        column = command_output.split('column')[1].split(':')[0].split(',')[0].delete(' ')
@Shylpx this is the command output:

```
"ERROR 1: COPY statement failed.\nERROR:  date/time field value out of range: \"2021/02/29 00:00:00\"\nCONTEXT:  COPY importer_244f5bf7196b4d2a8e791bbc59ef891c, line 89, column time: \"2021/02/29 00:00:00\"\n\n"
```

I've been reviewing the proposed changes and I've introduced all of them, but I don't really know how to replace the split functions using regular expressions!

2021-08-09 14:54 UTC, Shylpx commented on services/importer/lib/importer/loader.rb
> +        column = command_output.split('column')[1].split(':')[0].split(',')[0].delete(' ')
@moicalcob You can use something like the following to capture the number of the line:

```
line = /(?<=, line )\d+(?=,)/.match(command_output).to_s.to_i
```
I invite you to create the one for the name of the colum :). Resources:

- Information about regular expressions, incluiding look ahead/look behind: https://www.regular-expressions.info/lookaround.html.
- You can test your regular expresions live with this tool: https://rubular.com/
- And the documentation about the Regexp Ruby class: https://ruby-doc.org/core-2.4.0/Regexp.html

2021-08-11 15:13 UTC, Shylpx approved these changes

2021-08-12 06:35 UTC, amiedes approved these changes

2021-08-19 09:37 UTC, merged